#!/usr/bin/perl

for $file (</data/data/census/2010/www2.census.gov/census_2010/04-Summary_File_1/*/*geo2010.sf1>) {
	print STDERR "$file\n";

	open(GEO, "$file");
	while (<GEO>) {
		$sumlev = substr($_, 8, 3);
		next if $sumlev != 101;

		$land = substr($_, 198, 14);
		$water = substr($_, 212, 14);

		$lat = substr($_, 336, 11);
		$lon = substr($_, 347, 12);

		$pop = substr($_, 318, 9);
		$units = substr($_, 327, 9);

		$block = substr($_, 28 - 1, 2) .
			substr($_, 30 - 1, 3) .
			substr($_, 55 - 1, 6) .
			substr($_, 62 - 1, 4);

		$lat =~ s/ //g;
		$lon =~ s/ //g;
		$land =~ s/ //g;
		$water =~ s/ //g;
		$pop =~ s/ //g;
		$units =~ s/ //g;

		$lat =~ s/^\+//;
		$lon =~ s/^\+//;
		$lat =~ s/^-0*/-/;
		$lon =~ s/^-0*/-/;

		$lat{$block} = $lat;
		$lon{$block} = $lon;

		$land{$block} = $land;
		$water{$block} = $water;
		$pop{$block} = $pop;
		$units{$block} = $units;
	}
	close(FILE);
}

for $file (<2013/lehd.ces.census.gov/data/lodes/LODES7/*/wac/*_wac_S000_JT00_2013.csv.gz>) {
	print STDERR "$file\n";
	open(IN, "zcat $file |");
	while (<IN>) {
		chomp;
		($src, $rest) = split(/,/, $_, 2);

		if ($lat{$src} eq "" || $lat{$src} eq "") {
			print STDERR "$src $dest\n";
		} else {
			print "$_,$lat{$src},$lon{$src},$land{$src},$water{$src},$pop{$src},$units{$src}\n";
			$seen{$src} = 1;
		}
	}
	close(IN);
}

for $src (sort(keys(%lat))) {
	next if $seen{$src};
	next if $pop{$src} == 0;

	print "$src,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,$lat{$src},$lon{$src},$land{$src},$water{$src},$pop{$src},$units{$src}\n";
}
